version: "3"

services:
  nginx:
    container_name: nginx
    image: "jwilder/nginx-proxy:alpine"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HSTS=off
networks:
  default:
    external: true
    name: nghminh163-network
